/* ═══════════════════════════════════════════════════════════════
   BỘ 200+ BIẾN TẤU & MEME STICKER CAPYBARA CHUẨN GỐC
   (Mắt chỉ có chấm tròn hoặc 2 gạch nhỏ • Miệng T + Y ngược)
   
   Phân loại 5 nhóm lớn khớp với 168 ô câu thoại & ngữ cảnh:
   1. Đời thường & Thư giãn (40 dáng)
   2. Trader, Tài chính & Chứng khoán (40 dáng)
   3. Ẩm thực & Thưởng thức (40 dáng)
   4. Hóa trang & Nghề nghiệp (40 dáng)
   5. Thể thao, Dã ngoại & Âm nhạc (45 dáng)
   ═══════════════════════════════════════════════════════════════ */

export interface CapyMemeItem {
  id: string;
  name: string;
  category: 'CHILL' | 'TRADING' | 'FOOD' | 'COSPLAY' | 'SPORTS';
  categoryName: string;
  mat: 'gach' | 'cham'; // Gạch nhỏ hoặc Chấm tròn
  phuKien: string;
  description: string;
}

export const CAPY_200_MEMES: CapyMemeItem[] = [
  /* ══ NHÓM 1: ĐỜI THƯỜNG & THƯ GIÃN (1 - 40) ══ */
  { id: 'm_01', name: 'Đội 1 quả quýt có cuống lá', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'cam_don', description: 'Capy biểu tượng đội 1 quả quýt cam có cuống lá xanh' },
  { id: 'm_02', name: 'Đội tháp 3 quả cam chồng lên nhau', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'thap_3_cam', description: 'Ba quả cam vàng cam xếp chồng thăng bằng' },
  { id: 'm_03', name: 'Ngâm bồn tắm gỗ Onsen đắp khăn vuông', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'bon_go_onsen', description: 'Ngâm mình thư thái trong thùng gỗ nước khoáng nóng' },
  { id: 'm_04', name: 'Nằm sấp duỗi 4 chân (Bánh mì Loaf)', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'loaf_banh_mi', description: 'Nằm ườn hình ổ bánh mì siêu lười' },
  { id: 'm_05', name: 'Cầm bảng hiệu giơ dấu OK', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'bang_ok', description: 'Giơ bảng OK tán thành 100%' },
  { id: 'm_06', name: 'Đeo kính râm đen cực ngầu', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'kinh_ram', description: 'Kính râm đen ngầu như đại gia' },
  { id: 'm_07', name: 'Đội nón lá truyền thống Việt Nam', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'non_la', description: 'Nón lá chóp tre dân dã' },
  { id: 'm_08', name: 'Đeo ba lô con ếch xanh', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'balo_ech', description: 'Đeo ba lô ếch xanh chuẩn bị đi làm' },
  { id: 'm_09', name: 'Ôm gối ôm ngủ khò khò (zzz)', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'goi_om_zzz', description: 'Ôm gối ngủ say giấc nồng' },
  { id: 'm_10', name: 'Tắm bọt xà phòng bong bóng', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'bong_bong_tam', description: 'Bong bóng xà phòng ngũ sắc bay lơ lửng' },
  { id: 'm_11', name: 'Cầm quạt giấy phẩy gió', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'quat_giay', description: 'Quạt nan giấy phe phẩy ngày hè' },
  { id: 'm_12', name: 'Cầm ô nhỏ che mưa', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'o_che_mua', description: 'Chiếc ô màu vàng tươi dưới mưa rơi' },
  { id: 'm_13', name: 'Đeo nơ đỏ cổ áo xinh xắn', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'no_do', description: 'Chiếc nơ đỏ tươi tắn trước ngực' },
  { id: 'm_14', name: 'Đội mũ len cục bông mùa đông', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'mu_len_bong', description: 'Mũ len đỏ ấm áp có cục bông tròn' },
  { id: 'm_15', name: 'Cầm chong chóng 4 cánh quay tít', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'chong_chong', description: 'Chong chóng cầu vồng đón gió' },
  { id: 'm_16', name: 'Ngồi thiền hoa sen tỏa hào quang', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'thien_hoa_sen', description: 'Tọa thiền thanh tịnh tâm bất biến' },
  { id: 'm_17', name: 'Tưới bình hoa sen đá nhỏ', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'binh_tuoi_hoa', description: 'Cầm bình tưới cây xanh mướt' },
  { id: 'm_18', name: 'Cầm đèn pin soi đêm', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'den_pin', description: 'Đèn pin chiếu vệt sáng vàng' },
  { id: 'm_19', name: 'Cầm cốc nước dừa cắm ống hút', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'qua_dua_tuoi', description: 'Quả dừa tươi mát lạnh bên bờ biển' },
  { id: 'm_20', name: 'Thả tim đỏ bay lơ lửng', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'tim_bay', description: 'Những trái tim hồng bay bổng' },
  { id: 'm_21', name: 'Đội mũ phớt vintage', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'mu_phot', description: 'Mũ phớt phong cách quý ông' },
  { id: 'm_22', name: 'Đeo khăn quàng cổ đỏ', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'khan_quang', description: 'Khăn len quàng cổ ấm áp' },
  { id: 'm_23', name: 'Cầm cành hoa cúc họa mi', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'hoa_cuc', description: 'Bông hoa cúc trắng nhụy vàng' },
  { id: 'm_24', name: 'Cầm bóng bay hình trái tim', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'bong_bay_tim', description: 'Bóng bay đỏ bay lơ lửng' },
  { id: 'm_25', name: 'Đội vương miện hoàng gia', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'vuong_mien', description: 'Vương miện vàng đính ngọc quý' },
  { id: 'm_26', name: 'Cầm gương soi nhan sắc', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'guong_soi', description: 'Gương tròn soi gương mặt bầu bĩnh' },
  { id: 'm_27', name: 'Đeo kính cận ngố tri thức', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'kinh_can', description: 'Kính gọng tròn bác học' },
  { id: 'm_28', name: 'Cầm bảng chấm điểm 10/10', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'diem_10', description: 'Giơ biển điểm 10 tuyệt đối' },
  { id: 'm_29', name: 'Đắp mặt nạ dưa chuột dưỡng da', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'mat_na_dua', description: '2 lát dưa chuột đắp mắt thư giãn' },
  { id: 'm_30', name: 'Đội mũ sinh nhật chóp nón', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'mu_sinh_nhat', description: 'Mũ chóp sinh nhật nhiều màu' },
  { id: 'm_31', name: 'Cầm cành cỏ 4 lá may mắn', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'co_4_la', description: 'Cỏ 4 lá xanh mang lại tài lộc' },
  { id: 'm_32', name: 'Đeo cà vạt sọc chéo', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'ca_vat', description: 'Cà vạt xanh kẻ đỏ lịch lãm' },
  { id: 'm_33', name: 'Cầm chuông gió leng keng', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'chuong_gio', description: 'Chuông gió pha lê reo vui' },
  { id: 'm_34', name: 'Cầm tách trà hoa cúc bốc khói', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'tach_tra_nong', description: 'Tách trà thảo mộc ấm áp' },
  { id: 'm_35', name: 'Ôm chú gấu bông mini', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'gau_bong', description: 'Chú gấu bông nhỏ màu nâu' },
  { id: 'm_36', name: 'Đội vòng nguyệt quế vinh quang', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'nguyet_que', description: 'Vòng lá xanh vinh quang chiến thắng' },
  { id: 'm_37', name: 'Cầm quả cầu tuyết mùa đông', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'cau_tuyet', description: 'Quả cầu thủy tinh có bông tuyết rơi' },
  { id: 'm_38', name: 'Cầm kính 3D xem phim', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'cham', phuKien: 'kinh_3d', description: 'Kính 3D gọng xanh đỏ rạp chiếu phim' },
  { id: 'm_39', name: 'Thổi bong bóng kẹo cao su', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'bong_keo_cao_su', description: 'Bong bóng kẹo hồng phồng to' },
  { id: 'm_40', name: 'Cầm quạt điện mini cầm tay', category: 'CHILL', categoryName: 'Đời thường & Chill', mat: 'gach', phuKien: 'quat_dien_mini', description: 'Quạt tích điện nhỏ xinh xua tan nóng' },

  /* ══ NHÓM 2: TRADER, TÀI CHÍNH & CHỨNG KHOÁN (41 - 80) ══ */
  { id: 'm_41', name: 'Ôm laptop gõ phím cày chart nến', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'laptop_chart', description: 'Laptop hiển thị đồ thị nến xanh đỏ' },
  { id: 'm_42', name: 'Cầm kính lúp soi nến bứt phá', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'kinh_lup_soi_nen', description: 'Kính lúp phóng to mô hình bứt phá' },
  { id: 'm_43', name: 'Cầm bảng CE tím trần bùng nổ', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'bang_ce_tim', description: 'Bảng số điện tử tím trần rực rỡ' },
  { id: 'm_44', name: 'Ôm bao tải tiền VND nặng trĩu', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'bao_tien', description: 'Bao tải tiền đầy ắp lộc tài' },
  { id: 'm_45', name: 'Cầm máy tính Casio tính lãi PnL', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'may_tinh_casio', description: 'Bấm máy tính cộng dồn lợi nhuận' },
  { id: 'm_46', name: 'Giơ cờ xanh MUA (BUY SIGNAL)', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'co_mua_xanh', description: 'Lá cờ xanh lục lệnh mua gom' },
  { id: 'm_47', name: 'Giơ cờ đỏ BÁN (TAKE PROFIT)', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'co_ban_do', description: 'Lá cờ đỏ chốt lời bảo toàn vốn' },
  { id: 'm_48', name: 'Đội mũ bảo hiểm phái sinh', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'mu_bao_hiem', description: 'Mũ bảo hiểm an toàn vượt nhịp rung lắc' },
  { id: 'm_49', name: 'Đeo đồng hồ vàng đếm giờ ATO', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'dong_ho_vang', description: 'Đồng hồ vàng sang trọng canh 09:00' },
  { id: 'm_50', name: 'Cầm chuông vàng mở phiên giao dịch', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'chuong_vang', description: 'Rung chuông mở bát phiên mới' },
  { id: 'm_51', name: 'Đọc báo tài chính VnEconomy', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'to_bao_tai_chinh', description: 'Cầm tờ báo đọc tin tức vĩ mô' },
  { id: 'm_52', name: 'Cầm thỏi vàng SJC 9999', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'thoi_vang', description: 'Thỏi vàng nguyên chất lấp lánh' },
  { id: 'm_53', name: 'Cầm con bò xanh Bull Market', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'bo_bull_xanh', description: 'Tượng bò tót xanh thị trường tăng trưởng' },
  { id: 'm_54', name: 'Cầm tấm séc triệu đô', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'tam_sec', description: 'Phiếu thu lợi nhuận tài khoản L7Sea' },
  { id: 'm_55', name: 'Cầm cúp vàng vô địch đầu tư', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'cup_vang', description: 'Chiếc cúp vinh danh trader xuất sắc' },
  { id: 'm_56', name: 'Cầm điện thoại check số dư NAV', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'dt_check_nav', description: 'Điện thoại màn hình CKV PRO xanh mướt' },
  { id: 'm_57', name: 'Cầm chìa khóa két sắt bảo mật', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'chia_khoa_ket', description: 'Chìa khóa vàng mã PIN 542463' },
  { id: 'm_58', name: 'Đội mũ tốt nghiệp kinh tế', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'mu_tot_nghiep', description: 'Mũ cử nhân quản trị tài chính' },
  { id: 'm_59', name: 'Cầm bút ký hợp đồng mua cổ phần', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'but_ky_deal', description: 'Bút máy mạ vàng ký deal Margin' },
  { id: 'm_60', name: 'Cầm huy hiệu CKV PRO bằng vàng', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'huy_hieu_ckv', description: 'Huy hiệu kim loại sáng loáng' },
  { id: 'm_61', name: 'Cầm mũi tên xanh hướng thẳng lên trời', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'mui_ten_xanh', description: 'Mũi tên tăng trưởng dốc đứng' },
  { id: 'm_62', name: 'Cầm la bàn tìm xu hướng dòng tiền', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'la_ban_dong_tien', description: 'La bàn vàng định hướng VN50' },
  { id: 'm_63', name: 'Cầm cặp tài liệu da giám đốc', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'cap_da_sep', description: 'Cặp da công tác tài chính' },
  { id: 'm_64', name: 'Cầm đồng tiền vàng Bitcoin / Crypto', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'dong_tien_vang', description: 'Đồng xu tài sản số lấp lánh' },
  { id: 'm_65', name: 'Cầm cái búa gõ phán quyết lệnh', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'bua_phan_quyet', description: 'Búa gỗ chủ tọa chốt phiên' },
  { id: 'm_66', name: 'Cầm còi lệnh bắt đầu phiên ATO', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'coi_ato', description: 'Còi bạc mở màn phiên giao dịch' },
  { id: 'm_67', name: 'Đeo tai nghe tổng đài tư vấn lệnh', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'tai_nghe_broker', description: 'Tai nghe mic chuyên gia phân tích' },
  { id: 'm_68', name: 'Cầm thước kẻ vẽ đường MA20', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'thuoc_ke_chart', description: 'Thước kẻ đo kênh giá xu hướng' },
  { id: 'm_69', name: 'Cầm cục nam châm hút tiền tài', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'nam_cham_hut_tien', description: 'Nam châm đỏ hút đồng xu vàng' },
  { id: 'm_70', name: 'Cầm ống nhòm ngắm mục tiêu 1M', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'ong_nhom_target', description: 'Ống nhòm viễn cảnh mục tiêu giá xa' },
  { id: 'm_71', name: 'Cầm con dấu đỏ ĐÃ KHỚP LỆNH', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'dau_khop_lenh', description: 'Con dấu mộc đỏ chứng nhận thành công' },
  { id: 'm_72', name: 'Cầm tấm khiên chống sập Stop Loss', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'khien_stop_loss', description: 'Tấm khiên thép bảo vệ tài khoản' },
  { id: 'm_73', name: 'Cầm phong bao lì xì cổ tức', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'bao_li_xi', description: 'Bao lì xì đỏ tươi chứa cổ tức tiền mặt' },
  { id: 'm_74', name: 'Cầm quả tạ nâng sức mạnh NAV', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'ta_suc_manh', description: 'Gia tăng sức mạnh tài sản ròng' },
  { id: 'm_75', name: 'Cầm bánh lái tàu trưởng vượt sóng', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'banh_lai_tau', description: 'Bánh lái gỗ điều hướng danh mục' },
  { id: 'm_76', name: 'Cầm ngọn đuốc thắp sáng cơ hội', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'ngon_duoc', description: 'Đuốc vàng soi sáng siêu cổ' },
  { id: 'm_77', name: 'Cầm cuốn sổ nhật ký bìa da nâu', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'so_nhat_ky', description: 'Sổ ghi chép giao dịch kỷ luật' },
  { id: 'm_78', name: 'Cầm đồng hồ cát đo thời gian T+2.5', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'dong_ho_cat', description: 'Đồng hồ cát đo nhịp hàng về' },
  { id: 'm_79', name: 'Cầm hạt kim cương xanh giá trị', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'gach', phuKien: 'kim_cuong', description: 'Viên kim cương đại diện cổ phiếu cơ bản' },
  { id: 'm_80', name: 'Cầm loa phóng thanh hô hào đón sóng', category: 'TRADING', categoryName: 'Trader & Chứng khoán', mat: 'cham', phuKien: 'loa_thong_bao', description: 'Loa đỏ thông báo tín hiệu MUA' },

  /* ══ NHÓM 3: ẨM THỰC & THƯỞNG THỨC (81 - 120) ══ */
  { id: 'm_81', name: 'Ăn miếng dưa hấu đỏ mọng ngọt', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'mieng_dua_hau', description: 'Miếng dưa hấu hạt đen giải nhiệt' },
  { id: 'm_82', name: 'Uống ly trà sữa trân châu full topping', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'tra_sua_boba', description: 'Ly trà sữa cắm ống hút to bự' },
  { id: 'm_83', name: 'Xì xụp bát mì ramen nóng hổi', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'to_ramen', description: 'Tô mì Nhật trứng lòng đào bốc khói' },
  { id: 'm_84', name: 'Cầm que kem ốc quế dâu tây', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'kem_oc_que', description: 'Kem ốc quế mát lạnh ngọt ngào' },
  { id: 'm_85', name: 'Ăn miếng pizza phô mai kéo sợi', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'mieng_pizza', description: 'Miếng bánh pizza thơm lừng' },
  { id: 'm_86', name: 'Cắn bánh mì kẹp xúc xích hotdog', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'banh_hotdog', description: 'Bánh mì xúc xích rưới sốt mù tạt' },
  { id: 'm_87', name: 'Gặm củ cà rốt giòn ngọt', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'cu_ca_rot', description: 'Củ cà rốt cam có cuống lá tươi' },
  { id: 'm_88', name: 'Cầm ly cà phê phin Việt Nam bốc khói', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'cham', phuKien: 'ca_phe_phin', description: 'Tách cà phê đậm đà tỉnh táo buổi sáng' },
  { id: 'm_89', name: 'Cầm bánh donut socola rắc kẹo cốm', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'banh_donut', description: 'Bánh vòng donut ngọt ngào' },
  { id: 'm_90', name: 'Ăn quả bơ xanh béo ngậy', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'qua_bo', description: 'Nửa quả bơ sáp dinh dưỡng' },
  { id: 'm_91', name: 'Cầm chùm nho tím ngọt lịm', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'chum_nho_tim', description: 'Chùm nho tím tài lộc' },
  { id: 'm_92', name: 'Ăn bánh bao nhân thịt nóng hổi', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'banh_bao', description: 'Bánh bao trắng nõn bốc khói' },
  { id: 'm_93', name: 'Cầm quả dâu tây đỏ thắm', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'qua_dau_tay', description: 'Trái dâu tây căng mọng' },
  { id: 'm_94', name: 'Cầm miếng sushi cá hồi tươi ngon', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'sushi_ca_hoi', description: 'Cơm cuộn cá hồi Nhật Bản' },
  { id: 'm_95', name: 'Uống hộp sữa tươi tiệt trùng', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'cham', phuKien: 'hop_sua_tuoi', description: 'Hộp sữa bò tươi dinh dưỡng' },
  { id: 'm_96', name: 'Cầm bắp ngô nướng thơm phức', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'bap_ngo', description: 'Bắp ngô vàng óng ả' },
  { id: 'm_97', name: 'Ăn bánh sừng bò croissant bơ', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'banh_croissant', description: 'Bánh mì sừng bò kiểu Pháp' },
  { id: 'm_98', name: 'Cầm quả chuối vàng chín cây', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'qua_chuoi', description: 'Trái chuối vàng tươi ngon' },
  { id: 'm_99', name: 'Cầm cây kẹo mút cầu vồng xoắn ốc', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'keo_mut', description: 'Kẹo mút tròn sặc sỡ' },
  { id: 'm_100', name: 'Ăn bánh cupcake kem dâu', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'cupcake', description: 'Bánh bông lan phủ kem hồng' },
  { id: 'm_101', name: 'Cầm miếng phô mai vàng lỗ chỗ', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'pho_mai', description: 'Miếng phô mai Thụy Sĩ béo ngậy' },
  { id: 'm_102', name: 'Cầm củ khoai lang nướng mật', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'khoai_lang', description: 'Khoai nướng ấm lòng ngày đông' },
  { id: 'm_103', name: 'Cầm đùi gà rán giòn rụm', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'dui_ga_ran', description: 'Đùi gà chiên vàng ươm' },
  { id: 'm_104', name: 'Cầm quả táo đỏ bóng bẩy', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'cham', phuKien: 'qua_tao_do', description: 'Trái táo đỏ tươi ngon giòn rụm' },
  { id: 'm_105', name: 'Cầm hộp bắp rang bơ xem phim', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'cham', phuKien: 'bap_rang_bo', description: 'Hộp bắp rang bơ thơm ngậy rạp phim' },
  { id: 'm_106', name: 'Uống lon nước ngọt có gas', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'lon_nuoc_ngot', description: 'Lon nước ngọt sảng khoái' },
  { id: 'm_107', name: 'Cầm củ cải trắng to tròn', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'cham', phuKien: 'cu_cai_trang', description: 'Củ cải ngọt mát' },
  { id: 'm_108', name: 'Ăn thanh socola đen nguyên chất', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'thanh_socola', description: 'Thanh socola bẻ làm đôi' },
  { id: 'm_109', name: 'Cầm bát súp nấm thơm ngào ngạt', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'bat_sup_nam', description: 'Tô súp nóng ấm bụng' },
  { id: 'm_110', name: 'Ăn quả đào hồng mọng nước', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'qua_dao_hong', description: 'Trái đào tiên thơm ngọt' },
  { id: 'm_111', name: 'Cầm xiên que cá viên chiên', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'xien_ca_vien', description: 'Xiên que ăn vặt đường phố' },
  { id: 'm_112', name: 'Cầm bánh tráng trộn tắc ớt', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'banh_trang_tron', description: 'Món ăn vặt đậm vị' },
  { id: 'm_113', name: 'Uống ly sinh tố bơ mãng cầu', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'sinh_to_bo', description: 'Ly sinh tố xanh thơm béo' },
  { id: 'm_114', name: 'Cầm củ hành tây tím ngọt', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'cham', phuKien: 'hanh_tay_tim', description: 'Củ hành tây màu tím đẹp mắt' },
  { id: 'm_115', name: 'Ăn chiếc bánh quy socola chip', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'banh_quy_chip', description: 'Bánh cookie giòn rụm' },
  { id: 'm_116', name: 'Cầm quả lựu đỏ hạt ngọc', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'cham', phuKien: 'qua_luu', description: 'Trái lựu đỏ tượng trưng phú quý' },
  { id: 'm_117', name: 'Cầm xiên thịt nướng BBQ', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'xien_bbq', description: 'Thịt nướng thơm nức mũi' },
  { id: 'm_118', name: 'Uống ấm trà sen Tây Hồ', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'am_tra_sen', description: 'Ấm trà gốm hương sen thanh tao' },
  { id: 'm_119', name: 'Cầm miếng dưa lưới vàng ruộm', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'dua_luoi', description: 'Dưa lưới Nhật Bản ngọt mát' },
  { id: 'm_120', name: 'Ăn hũ sữa chua dầm hạt chia', category: 'FOOD', categoryName: 'Ẩm thực & Món ngon', mat: 'gach', phuKien: 'sua_chua', description: 'Hũ sữa chua mát lành tiêu hóa tốt' },

  /* ══ NHÓM 4: HÓA TRANG & NGHỀ NGHIỆP (121 - 160) ══ */
  { id: 'm_121', name: 'Siêu nhân áo choàng đỏ bay lượn', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'sieu_nhan_choang', description: 'Áo choàng siêu nhân đỏ bay phần phật' },
  { id: 'm_122', name: 'Phi hành gia NASA mũ vũ trụ', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'phi_hanh_gia', description: 'Mũ vũ trụ phi hành gia thám hiểm không gian' },
  { id: 'm_123', name: 'Đầu bếp MasterChef cầm muôi gỗ', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'dau_bep_muoi', description: 'Mũ đầu bếp trắng cao cầm muôi nấu ăn' },
  { id: 'm_124', name: 'Thám tử Sherlock Holmes ngậm tẩu', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'tham_tu_tau', description: 'Mũ thám tử ca rô và kính lúp phá án' },
  { id: 'm_125', name: 'Phù thủy quyền năng gậy phép thuật', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'phu_thuy_gay', description: 'Mũ chóp phù thủy sao vàng và gậy phép' },
  { id: 'm_126', name: 'Bác sĩ đeo ống nghe y tế', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'bac_si_ong_nghe', description: 'Áo blouse trắng đeo ống nghe khám bệnh' },
  { id: 'm_127', name: 'Cảnh sát mũ kepi giữ trật tự', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'canh_sat_kepi', description: 'Mũ cảnh sát gắn huy hiệu ngôi sao' },
  { id: 'm_128', name: 'Kỹ sư công trình mũ bảo hộ vàng', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'ky_su_mu_vang', description: 'Mũ bảo hộ công trường xây dựng' },
  { id: 'm_129', name: 'Họa sĩ đội mũ beret cầm bảng pha màu', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'hoa_si_beret', description: 'Mũ beret Pháp và bảng vẽ nghệ thuật' },
  { id: 'm_130', name: 'Nhà khoa học kính bảo hộ ống nghiệm', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'nha_khoa_hoc', description: 'Cầm ống nghiệm hóa học phát sáng' },
  { id: 'm_131', name: 'Thuyền trưởng cướp biển chắp mắt', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'cuop_bien_chap_mat', description: 'Mũ thuyền trưởng cờ đầu lâu' },
  { id: 'm_132', name: 'Võ sĩ đai đen Karate dũng mãnh', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'vo_si_karate', description: 'Võ phục trắng thắt đai đen' },
  { id: 'm_133', name: 'Hiệp sĩ giáp sắt cầm khiên hiệp sĩ', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'hiep_si_giap', description: 'Mũ giáp hiệp sĩ thời trung cổ' },
  { id: 'm_134', name: 'Thợ lặn bình dưỡng khí kính bơi', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'tho_lan_binh_khi', description: 'Bộ đồ lặn biển ngắm san hô' },
  { id: 'm_135', name: 'Cao bồi Viễn Tây mũ vành rộng', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'cao_boi_mu_vanh', description: 'Mũ cao bồi da nâu phong trần' },
  { id: 'm_136', name: 'Thần tài cầm thỏi vàng đỏ', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'than_tai_do', description: 'Mũ cánh chuồn đỏ thần tài gõ cửa' },
  { id: 'm_137', name: 'Ông già Noel túi quà Giáng sinh', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'ong_gia_noel', description: 'Mũ đỏ viền lông trắng phát quà' },
  { id: 'm_138', name: 'Chú hề mũi đỏ tóc xoăn vui nhộn', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'chu_he_mui_do', description: 'Mũi tròn đỏ chú hề rạp xiếc' },
  { id: 'm_139', name: 'Ninja bí ẩn khăn trùm đen', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'ninja_den', description: 'Khăn bịt mặt ninja huyền bí' },
  { id: 'm_140', name: 'Thợ săn kho báu mũ tai bèo', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'tho_san_tai_beo', description: 'Mũ dã ngoại thám hiểm rừng sâu' },
  { id: 'm_141', name: 'Nhân viên văn phòng đeo thẻ nhân viên', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'the_nhan_vien', description: 'Dây đeo thẻ công sở CKV PRO' },
  { id: 'm_142', name: 'Thợ may thước dây quàng cổ', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'tho_may_thuoc', description: 'Thước dây đo cắt may vest' },
  { id: 'm_143', name: 'Lính cứu hỏa mũ đỏ vòi rồng', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'cuu_hoa_mu_do', description: 'Mũ lính cứu hỏa dũng cảm' },
  { id: 'm_144', name: 'Gamer chuyên nghiệp tai nghe RGB', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'gamer_tai_nghe', description: 'Tai nghe chụp tai có đèn led đổi màu' },
  { id: 'm_145', name: 'Nhà khảo cổ học bàn chải hóa thạch', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'khao_co_hoc', description: 'Kính lúp tìm cổ vật ngàn năm' },
  { id: 'm_146', name: 'Phi công bầu trời kính phi công', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'phi_cong_kinh', description: 'Kính da phi công lái máy bay' },
  { id: 'm_147', name: 'Người làm vườn kéo tỉa cành', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'lam_vuon_keo', description: 'Tạp dề vải thô chăm sóc cây cảnh' },
  { id: 'm_148', name: 'Vua sư tử áo choàng nhung đỏ', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'vua_choang_nhung', description: 'Vương trượng quyền uy' },
  { id: 'm_149', name: 'Thủ môn bóng đá găng tay bắt dính', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'gang_tay_thu_mon', description: 'Găng tay thủ môn giữ sạch lưới' },
  { id: 'm_150', name: 'Thợ cơ khí cờ lê mỏ lết', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'co_le_mo_let', description: 'Cờ lê sửa chữa máy móc' },
  { id: 'm_151', name: 'Luật sư tập hồ sơ tài liệu', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'luat_su_ho_so', description: 'Tập hồ sơ bảo vệ quyền lợi đầu tư' },
  { id: 'm_152', name: 'Nhạc trưởng cây đũa chỉ huy dàn nhạc', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'nhac_truong_dua', description: 'Cây đũa baton chỉ huy giao hưởng' },
  { id: 'm_153', name: 'Thợ làm bánh tạp dề trắng', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'tho_banh_tap_de', description: 'Khuôn bánh nướng thơm phức' },
  { id: 'm_154', name: 'Bảo vệ ca đêm đèn pin áo xanh', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'bao_ve_den_pin', description: 'Canh gác an toàn tài khoản' },
  { id: 'm_155', name: 'Hướng dẫn viên du lịch cờ dẫn đoàn', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'huong_dan_vien', description: 'Lá cờ hướng dẫn tour' },
  { id: 'm_156', name: 'Trọng tài còi đen thẻ vàng', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'trong_tai_the_vang', description: 'Thẻ phạt cảnh báo vi phạm kỷ luật' },
  { id: 'm_157', name: 'Kiến trúc sư cuộn bản vẽ công trình', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'kien_truc_su', description: 'Bản vẽ kỹ thuật quy hoạch' },
  { id: 'm_158', name: 'Thợ điện kìm cách điện', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'tho_dien_kim', description: 'Đảm bảo dòng điện kết nối thông suốt' },
  { id: 'm_159', name: 'Dược sĩ lọ thuốc bổ vitamin', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'gach', phuKien: 'duoc_si_thuoc_bo', description: 'Vitamin bồi bổ sức khỏe cho trader' },
  { id: 'm_160', name: 'Thủ thư thư viện sách dày cộp', category: 'COSPLAY', categoryName: 'Hóa trang & Nghề nghiệp', mat: 'cham', phuKien: 'thu_thu_sach', description: 'Tủ sách kinh điển chứng khoán' },

  /* ══ NHÓM 5: THỂ THAO, DÃ NGOẠI & ÂM NHẠC (161 - 205) ══ */
  { id: 'm_161', name: 'Cưỡi chú rùa xanh đi dạo thong dong', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'cuoi_rua_xanh', description: 'Ngồi trên mai rùa xanh đi dạo siêu chill' },
  { id: 'm_162', name: 'Trượt ván skateboard vèo vèo', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'van_truot_skate', description: 'Ván trượt 4 bánh màu đỏ phong cách' },
  { id: 'm_163', name: 'Đạp xe đạp mini có giỏ hoa', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'xe_dap_mini', description: 'Xe đạp màu xanh có giỏ hoa cúc' },
  { id: 'm_164', name: 'Bơi phao con vịt vàng toe toét', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'phao_vit_vang', description: 'Phao bơi tròn hình chú vịt vàng' },
  { id: 'm_165', name: 'Nâng tạ tay tập gym lên cơ', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'ta_tay_gym', description: 'Quả tạ sắt rèn luyện thể lực' },
  { id: 'm_166', name: 'Thổi kèn Saxophone du dương', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'ken_saxophone', description: 'Cây kèn đồng saxophone giai điệu êm ái' },
  { id: 'm_167', name: 'Gảy đàn guitar acoustic gỗ', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'dan_guitar', description: 'Đàn guitar thùng mộc mạc' },
  { id: 'm_168', name: 'Chụp ảnh máy cơ vintage cổ điển', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'may_anh_co', description: 'Máy ảnh chụp phim bắt trọn khoảnh khắc' },
  { id: 'm_169', name: 'Câu cá bên bờ suối cần câu trúc', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'can_cau_ca', description: 'Cần câu trúc và xô cá nhỏ' },
  { id: 'm_170', name: 'Chèo thuyền kayak vượt thác ghềnh', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'thuyen_kayak', description: 'Mái chèo đôi lướt trên dòng sông' },
  { id: 'm_171', name: 'Đá quả bóng đá sọc đen trắng', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'qua_bong_da', description: 'Quả bóng da lăn tròn sân cỏ' },
  { id: 'm_172', name: 'Ném bóng rổ vào rổ ghi 3 điểm', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'bong_ro_cam', description: 'Quả bóng rổ cam nảy tưng tưng' },
  { id: 'm_173', name: 'Cầm vợt tennis đánh banh nỉ', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'vot_tennis', description: 'Vợt tennis và quả bóng nỉ vàng' },
  { id: 'm_174', name: 'Cầm gậy golf đánh cú Hole-in-one', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'gay_golf', description: 'Gậy golf đánh bóng vào lỗ cờ xanh' },
  { id: 'm_175', name: 'Cắm trại bên lều bạt lửa trại', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'leu_cam_trai', description: 'Lều trại dã ngoại dưới bầu trời sao' },
  { id: 'm_176', name: 'Thả diều rồng bay cao trên đồi cỏ', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'con_dieu_bay', description: 'Cánh diều no gió bay vút' },
  { id: 'm_177', name: 'Chạy bộ thể dục băng đô thấm mồ hôi', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'bang_do_chay', description: 'Băng đô đỏ chạy bộ nâng cao sức bền' },
  { id: 'm_178', name: 'Chơi bóng chuyền bãi biển', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'bong_chuyen', description: 'Bóng chuyền cát biển hè' },
  { id: 'm_179', name: 'Tập yoga tư thế cây bách', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'tham_yoga', description: 'Thảm yoga hồng tĩnh tâm' },
  { id: 'm_180', name: 'Lướt sóng biển ván lướt xanh', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'van_luot_song', description: 'Lướt trên ngọn sóng bạc đầu' },
  { id: 'm_181', name: 'Chơi cờ vua quân Hậu trắng', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'quan_co_vua', description: 'Quân cờ vua chiến thuật đỉnh cao' },
  { id: 'm_182', name: 'Cầm gậy bóng chày vụt Home-run', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'gay_bong_chay', description: 'Gậy gỗ đánh bóng chày' },
  { id: 'm_183', name: 'Đeo găng tay đấm bốc boxing đỏ', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'gang_boxing', description: 'Găng đấm bốc thi đấu dũng mãnh' },
  { id: 'm_184', name: 'Chơi bóng bàn vợt gỗ đỏ', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'vot_bong_ban', description: 'Vợt bóng bàn và bóng nhựa trắng' },
  { id: 'm_185', name: 'Ném phi tiêu trúng tâm hồng tâm', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'bang_phi_tieu', description: 'Bảng phi tiêu Bullseye điểm tối đa' },
  { id: 'm_186', name: 'Chơi đàn vĩ cầm Violin réo rắt', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'dan_violin', description: 'Cây đàn violin gỗ cao cấp' },
  { id: 'm_187', name: 'Gõ trống Jazz tùng cắc tùng', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'bo_trong_jazz', description: 'Dàn trống jazz sôi động' },
  { id: 'm_188', name: 'Chơi đàn Piano phím đen trắng', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'dan_piano', description: 'Dương cầm hòa tấu êm dịu' },
  { id: 'm_189', name: 'Thổi sáo trúc ngân vang rừng tre', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'sao_truc', description: 'Ống sáo trúc mộc mạc quê hương' },
  { id: 'm_190', name: 'Gõ đàn phiến mộc Xylophone', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'dan_xylophone', description: 'Thanh gỗ âm sắc cầu vồng' },
  { id: 'm_191', name: 'Leo núi chống gậy leo núi', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'gay_leo_nui', description: 'Gậy trekking chinh phục đỉnh Fansipan' },
  { id: 'm_192', name: 'Trượt tuyết gậy trượt và ván tuyết', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'van_truot_tuyet', description: 'Lướt trên dốc tuyết trắng xóa' },
  { id: 'm_193', name: 'Nhảy dù lượn bầu trời lộng gió', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'du_luon', description: 'Dù lượn màu sắc bay trên mây' },
  { id: 'm_194', name: 'Bắn cung tên trúng hồng tâm 10', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'cung_ten', description: 'Cung tên truyền thống ngắm chuẩn' },
  { id: 'm_195', name: 'Nhảy dây thể dục 100 cái', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'day_nhay', description: 'Dây nhảy tay cầm gỗ rèn luyện dẻo dai' },
  { id: 'm_196', name: 'Chơi ném đĩa Frisbee bãi cỏ', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'dia_frisbee', description: 'Đĩa bay nhựa xanh ném xa' },
  { id: 'm_197', name: 'Đeo kính nhìn đêm thám hiểm', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'kinh_nhin_dem', description: 'Kính hồng ngoại quan sát ban đêm' },
  { id: 'm_198', name: 'Lái cano cao tốc xé sóng nước', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'cano_nuoc', description: 'Vô lăng cano lướt sóng biển' },
  { id: 'm_199', name: 'Lăn bóng hơi Zorbing khổng lồ', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'bong_zorbing', description: 'Quả bóng trong suốt lăn đồi' },
  { id: 'm_200', name: 'Đội vòng hoa nhiệt đới Hawaii', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'vong_hoa_hawaii', description: 'Vòng hoa sứ vàng chào đón mùa hè rực rỡ' },
  { id: 'm_201', name: 'Chơi kèn Harmonica bỏ túi', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'ken_harmonica', description: 'Kèn harmonica kim loại du ca' },
  { id: 'm_202', name: 'Đua xe Go-kart mini mũ bảo hiểm', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'xe_gokart', description: 'Xe đua tốc độ mini đường đua' },
  { id: 'm_203', name: 'Cưỡi cá heo phun nước vui vẻ', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'ca_heo_nuoc', description: 'Chú cá heo xanh bơi cùng Capy' },
  { id: 'm_204', name: 'Lắc xúc xắc may mắn đại cát', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'cham', phuKien: 'xuc_xac_tai_loc', description: 'Xúc xắc 6 mặt đỏ tươi tài lộc' },
  { id: 'm_205', name: 'Capy Hoàng Kim toàn năng tỏa sáng', category: 'SPORTS', categoryName: 'Thể thao & Dã ngoại', mat: 'gach', phuKien: 'capy_gold', description: 'Linh vật Capy phiên bản vàng 24K cực phẩm' }
];

/** Lấy ngẫu nhiên 1 meme trong 205 dáng */
export function layMemeNgauNhien(): CapyMemeItem {
  return CAPY_200_MEMES[Math.floor(Math.random() * CAPY_200_MEMES.length)];
}
